#! /usr/bin/env python


import sys
from datetime import datetime

def make_mtllib(file_name, material_name, texture_name):
    fmtl = open(file_name, 'w')
    fmtl.write("# generated by " + sys.argv[0] + "\n")
    fmtl.write("# " + datetime.now().strftime('%Y-%m-%d %H:%M:%S') + "\n" )
    fmtl.write("newmtl " + material_name + "\n")
    fmtl.write("Ka 1.0 1.0 1.0\n")
    fmtl.write("Kd 1.0 1.0 1.0\n")
    fmtl.write("Ks 0.0 0.0 0.0\n")
    fmtl.write("d .8\n")
    fmtl.write("Tr .2\n")
    fmtl.write("illum 1\n")
    fmtl.write("Ns 0.0\n")
    fmtl.write("map_Kd " + texture_name + "\n")
    fmtl.close()
